version:
  required: true
  type: string

pipeline_type:
  required: true
  type: string
  allowed:
    - built_in
    - byo_container

inference_type:
  required: true
  type: string
  allowed:
    - online
    - offline
    - batch

infra:
  required: false
  type: dict
  schema:
    terraform:
      required: false
      type: dict
      schema:
        destroy:
          required: true
          type:
            - string
            - boolean

info:
  required: true
  type: dict
  schema:
    owner_contact_email:
      required: true
      type: string
    tech_team_email:
      required: true
      type: string
    sigla:
      required: true
      type: string
    comunidade:
      required: true
      type: string
    squad:
      required: true
      type: string
    project_name:
      required: true
      type: string
    aws_account:
      required: true
      type: dict
      schema:
        name:
          required: true
          type: string
        number:
          required: true
          type: dict
          schema:
            analytics:
              required: true
              type:
                - number
                - string
            dev:
              required: true
              type:
                - number
                - string
            hom:
              required: true
              type:
                - number
                - string
            prod:
              required: true
              type:
                - number
                - string

parameters:
  required: true
  type: dict
  schema:
    experiment_id:
      required: true
      type: string
    id_mrm:
      required: true
      type:
        - number
        - string

network:
  required: true
  type: dict
  schema:
    subnets:
      required: true
      type: dict
      schema:
        subnet_id_one:
          required: true
          type: dict
          schema:
            analytics:
              required: true
              type: string
            dev:
              required: true
              type: string
            hom:
              required: true
              type: string
            prod:
              required: true
              type: string
        subnet_id_two:
          required: true
          type: dict
          schema:
            analytics:
              required: true
              type: string
            dev:
              required: true
              type: string
            hom:
              required: true
              type: string
            prod:
              required: true
              type: string
        subnet_id_three:
          required: true
          type: dict
          schema:
            dev:
              required: true
              type: string
            hom:
              required: true
              type: string
            prod:
              required: true
              type: string
    vpc:
      required: true
      type: dict
      schema:
        analytics:
          required: true
          type: string
        dev:
          required: true
          type: string
        hom:
          required: true
          type: string
        prod:
          required: true
          type: string

flavor:
  required: false
  type: dict
  schema:
    name:
      required: true
      type: string
    version:
      required: true
      type: string
    params:
      required: true
      type: dict
      schema:
        dev:
          required: false
          type: dict
          schema:
            enable_network_isolation:
              required: false
              type: boolean
            instance_type:
              required: false
              type: string
            inference_environment:
              required: false
              type: dict
              schema:
                LOG_LEVEL:
                  required: false
                  type: string
            data_capture:
              required: false
              type: dict
              schema:
                mode:
                  required: true
                  type: string
                percentage:
                  required: true
                  type: number
            autoscaling:
              required: false
              type: dict
              schema:
                min_capacity:
                  required: true
                  type: number
                max_capacity:
                  required: true
                  type: number
                max_requests_per_minute_per_instance:
                  required: true
                  type: number
                scale_in_cooldown_secs:
                  required: true
                  type: number
                scale_out_cooldown_secs:
                  required: true
                  type: number
        hom:
          required: false
          type: dict
          schema:
            enable_network_isolation:
              required: false
              type: boolean
            instance_type:
              required: false
              type: string
            inference_environment:
              required: false
              type: dict
              schema:
                LOG_LEVEL:
                  required: false
                  type: string
            data_capture:
              required: false
              type: dict
              schema:
                mode:
                  required: true
                  type: string
                percentage:
                  required: true
                  type: number
            autoscaling:
              required: false
              type: dict
              schema:
                min_capacity:
                  required: true
                  type: number
                max_capacity:
                  required: true
                  type: number
                max_requests_per_minute_per_instance:
                  required: true
                  type: number
                scale_in_cooldown_secs:
                  required: true
                  type: number
                scale_out_cooldown_secs:
                  required: true
                  type: number
        prod:
          required: false
          type: dict
          schema:
            enable_network_isolation:
              required: false
              type: boolean
            instance_type:
              required: false
              type: string
            inference_environment:
              required: false
              type: dict
              schema:
                LOG_LEVEL:
                  required: false
                  type: string
            data_capture:
              required: false
              type: dict
              schema:
                mode:
                  required: true
                  type: string
                percentage:
                  required: true
                  type: number
            autoscaling:
              required: false
              type: dict
              schema:
                min_capacity:
                  required: true
                  type: number
                max_capacity:
                  required: true
                  type: number
                max_requests_per_minute_per_instance:
                  required: true
                  type: number
                scale_in_cooldown_secs:
                  required: true
                  type: number
                scale_out_cooldown_secs:
                  required: true
                  type: number
